-- Extensão do Schema: Exercícios, Fichas e Treinos
-- Execute isso APÓS supabase-schema.sql

-- Tabela: exercises (Biblioteca de exercícios)
create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  muscle_group text not null check (muscle_group in ('Peito', 'Costas', 'Bíceps', 'Tríceps', 'Ombros', 'Quadríceps', 'Posterior', 'Glúteos', 'Panturrilha', 'Abdômen', 'Cardio', 'Corpo inteiro')),
  equipment text,
  category text,
  description text,
  instructions text,
  video_url text,
  image_url text,
  difficulty text check (difficulty in ('Iniciante', 'Intermediário', 'Avançado')),
  observations text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id)
);

create index if not exists exercises_muscle_group_idx on public.exercises (muscle_group);
create index if not exists exercises_active_idx on public.exercises (active);
create index if not exists exercises_created_by_idx on public.exercises (created_by);

-- Tabela: workout_plans (Fichas de treino melhorada)
create table if not exists public.workout_plans_v2 (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  professor_id uuid references public.profiles(id),
  name text not null,
  goal text,
  status text not null default 'ativa' check (status in ('ativa', 'inativa', 'revisao', 'finalizada')),
  observations text,
  start_date date not null default current_date,
  end_date date,
  frequency text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists workout_plans_v2_student_idx on public.workout_plans_v2 (student_id);
create index if not exists workout_plans_v2_professor_idx on public.workout_plans_v2 (professor_id);
create index if not exists workout_plans_v2_status_idx on public.workout_plans_v2 (status);

-- Tabela: workouts (Treinos dentro da ficha)
create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  workout_plan_id bigint not null references public.workout_plans_v2(id) on delete cascade,
  name text not null,
  day_of_week text check (day_of_week in ('Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo')),
  description text,
  order_number int not null default 1,
  observations text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists workouts_workout_plan_idx on public.workouts (workout_plan_id);
create index if not exists workouts_order_idx on public.workouts (order_number);

-- Tabela: workout_exercises (Exercícios dentro de um treino com configurações)
create table if not exists public.workout_exercises (
  id bigint generated by default as identity primary key,
  workout_id bigint not null references public.workouts(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id),
  order_number int not null default 1,
  series int not null default 3,
  repetitions text not null default '10', -- "10" ou "8-10" ou "10-15"
  weight numeric(8,2),
  weight_unit text default 'kg' check (weight_unit in ('kg', 'lbs', 'bodyweight')),
  rest_seconds int default 60,
  execution_time_seconds int,
  method text, -- superset, drop set, etc
  observations text,
  video_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists workout_exercises_workout_idx on public.workout_exercises (workout_id);
create index if not exists workout_exercises_exercise_idx on public.workout_exercises (exercise_id);
create index if not exists workout_exercises_order_idx on public.workout_exercises (order_number);

-- Triggers para updated_at
create or replace function public.set_updated_at_exercises()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists exercises_set_updated_at on public.exercises;
create trigger exercises_set_updated_at before update on public.exercises
for each row execute function public.set_updated_at_exercises();

drop trigger if exists workout_plans_v2_set_updated_at on public.workout_plans_v2;
create trigger workout_plans_v2_set_updated_at before update on public.workout_plans_v2
for each row execute function public.set_updated_at();

drop trigger if exists workouts_set_updated_at on public.workouts;
create trigger workouts_set_updated_at before update on public.workouts
for each row execute function public.set_updated_at();

drop trigger if exists workout_exercises_set_updated_at on public.workout_exercises;
create trigger workout_exercises_set_updated_at before update on public.workout_exercises
for each row execute function public.set_updated_at();

-- Row Level Security (RLS)
alter table public.exercises enable row level security;
alter table public.workout_plans_v2 enable row level security;
alter table public.workouts enable row level security;
alter table public.workout_exercises enable row level security;

-- RLS Policies: Exercises
create policy "anyone can read active exercises" on public.exercises for select using (active = true);
create policy "staff can manage exercises" on public.exercises for all using (auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin'));

-- RLS Policies: Workout Plans V2
create policy "students read own workout plans" on public.workout_plans_v2 for select using (student_id = auth.uid());
create policy "professors read student workout plans" on public.workout_plans_v2 for select using (professor_id = auth.uid() or auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin'));
create policy "staff manage all workout plans" on public.workout_plans_v2 for all using (auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin'));
create policy "professors create and edit own workout plans" on public.workout_plans_v2 for insert with check (professor_id = auth.uid() or auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin'));
create policy "professors update own workout plans" on public.workout_plans_v2 for update using (professor_id = auth.uid() or auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin'));

-- RLS Policies: Workouts (herda permissão da ficha)
create policy "students read own workouts" on public.workouts for select using (
  workout_plan_id in (select id from public.workout_plans_v2 where student_id = auth.uid())
);
create policy "professors manage workout plans" on public.workouts for all using (
  workout_plan_id in (select id from public.workout_plans_v2 where professor_id = auth.uid() or auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin'))
);
create policy "staff manage all workouts" on public.workouts for all using (auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin'));

-- RLS Policies: Workout Exercises
create policy "students read own exercises" on public.workout_exercises for select using (
  workout_id in (
    select w.id from public.workouts w
    join public.workout_plans_v2 wp on w.workout_plan_id = wp.id
    where wp.student_id = auth.uid()
  )
);
create policy "professors manage exercises" on public.workout_exercises for all using (
  workout_id in (
    select w.id from public.workouts w
    join public.workout_plans_v2 wp on w.workout_plan_id = wp.id
    where wp.professor_id = auth.uid() or auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin')
  )
);
create policy "staff manage all exercises" on public.workout_exercises for all using (auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin'));

-- Dados iniciais: Exercícios de exemplo
insert into public.exercises (name, muscle_group, equipment, category, difficulty, active) values
('Supino Reto', 'Peito', 'Halter', 'Força', 'Intermediário', true),
('Supino Inclinado', 'Peito', 'Halter', 'Força', 'Intermediário', true),
('Agachamento Livre', 'Quadríceps', 'Bodyweight', 'Força', 'Avançado', true),
('Leg Press 45°', 'Quadríceps', 'Máquina', 'Força', 'Iniciante', true),
('Rosca Direta', 'Bíceps', 'Halter', 'Força', 'Iniciante', true),
('Puxada Frontal', 'Costas', 'Máquina', 'Força', 'Iniciante', true),
('Remada Alta', 'Costas', 'Halter', 'Força', 'Intermediário', true),
('Desenvolvimento de Ombro', 'Ombros', 'Halter', 'Força', 'Intermediário', true),
('Cadeira Extensora', 'Quadríceps', 'Máquina', 'Isolamento', 'Iniciante', true),
('Mesa Flexora', 'Posterior', 'Máquina', 'Isolamento', 'Iniciante', true)
on conflict do nothing;
