create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'student' check (role in ('dev', 'admin', 'student')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists active boolean not null default true;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create index if not exists profiles_role_active_idx on public.profiles (role, active);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

create table if not exists public.workout_plans (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  goal text,
  frequency text,
  exercises jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.body_measurements (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  measured_at date not null default current_date,
  height numeric(5,2),
  weight numeric(5,2),
  shoulder numeric(5,2),
  chest numeric(5,2),
  waist numeric(5,2),
  hip numeric(5,2),
  arm_left numeric(5,2),
  arm_right numeric(5,2),
  thigh_left numeric(5,2),
  thigh_right numeric(5,2),
  leg_left numeric(5,2),
  leg_right numeric(5,2),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.workout_plans enable row level security;
alter table public.body_measurements enable row level security;

create policy "students can read own profile" on public.profiles for select using (auth.uid() = id);
create policy "staff can manage profiles" on public.profiles for all using (auth.uid() = id or auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin'));
create policy "students read own workouts" on public.workout_plans for select using (student_id = auth.uid());
create policy "staff manage workouts" on public.workout_plans for all using (student_id = auth.uid() or auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin'));
create policy "students read own measurements" on public.body_measurements for select using (student_id = auth.uid());
create policy "students manage own measurements" on public.body_measurements for insert with check (student_id = auth.uid());
create policy "students update own measurements" on public.body_measurements for update using (student_id = auth.uid());
create policy "staff manage measurements" on public.body_measurements for all using (student_id = auth.uid() or auth.jwt() -> 'app_metadata' ->> 'role' in ('dev', 'admin'));